// const gen1 = ["Tennessee Jed", "Jack Straw", "Sugaree", "Althea", "Delilah", "St Stephen", "Cassidy", "Cosmic Charlie", "Samson", "Stagger Lee"];
//bear data = {

// }
const gen1 = [
  {
    bearName: "Tennessee Jed",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "6-27-87",
    tourMemory: "The Boston Garden 90.20.91 second set opener Help>Slip>Fire nearly blew my mind! I've never heard a crowd cheer so loudly. EVERYONE in the place was expecting Franklin's and they play Fire! I loved it when they mixed things up.",
    venue: "Alpine Valley",
    imagePath: "#",
  },
  {
    bearName: "Jack Straw",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "4-20-69",
    tourMemory: "lorem ipsum",
    venue: "lorem ipsum venue",
    imagePath: "#",
  },
   {
    bearName: "Sugaree",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "04/12/82",
    tourMemory: "My favorite show was on 4/12/89 at Rosemont, my only birthday show! They played everything I wanted to hear that night - it was like they could read my mind! It was the best birthday EVER.",
    venue: "Nassau Coliseum",
    imagePath: "#",
  },
   {
    bearName: "Althea",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "08/12/79",
    tourMemory: "The first nite of the Radio City run I lost my ticket, my money, everything. I was just about to call it a night when someone came up to me, handed me a ticket, and told me to have a good time. It was my first miracle. I'll never forget it!",
    venue: "Red Rocks",
    imagePath: "#",
  },
   {
    bearName: "Delilah",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "06/21/80",
    tourMemory: "The greatest time ever. Europe 1990. I sold some nonessential things, like my car, to finance my trip. The ICC in Berlin was a cool venue & the lamps on the tables helped with writing my set list. The Deal to close the first set was THE BEST!",
    venue: "West High Auditorium",
    imagePath: "#",
  },
   {
    bearName: "St Stephen",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "01-20-88",
    tourMemory: "wherever he goes the people all complain",
    venue: "garden",
    imagePath: "#",
  },
   {
    bearName: "Cassidy",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "04-20-69",
    tourMemory: "flight of the seabirds",
    venue: "bus",
    imagePath: "#",
  },
   {
    bearName: "Cosmic Charlie",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "03-03-90",
    tourMemory: "going marching in",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Samson",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "04-20-69",
    tourMemory: "i would tear this old building down",
    venue: "old building",
    imagePath: "#",
  },
   {
    bearName: "Stagger Lee",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "05/10/91",
    tourMemory: "A Terrapin Station anytime, any place! I loved it when Jerry really stepped out like on High Time or Stella Blue and of course Terrapin. He was definitely the leader of the band - which reminds me, Ramble on Rose rules too!",
    venue: "Shoreline Amphitheatre",
    imagePath: "#",
  },
  
];

const gen2 = [
  {
    bearName: "Jerry",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "6-27-87",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Crazy Fingers",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Dark Star",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Daydream",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Dupree",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Ripple",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "Irie",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Sunshine",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Franklin",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Peggy-O",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

// GEN 3 

const gen3 = [
  {
    bearName: "Blues Man",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Foolish Heart",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "China Cat",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Haight",
    year: "1999",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Ashbury",
    year: "1999",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Reuben",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "August West",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Daisy",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Pearly Baker",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Doodah Man",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Uncle Sam",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Esau",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
]

const gen4 = [
  {
    bearName: "",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
]

const gen5 = [
  {
    bearName: "",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
]
const gen6 = [
   {
    bearName: "",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
]
const gen7 = [
   {
    bearName: "",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
]
const gen8 = [
   {
    bearName: "",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
]
const gen9 = [
   {
    bearName: "",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
]
const gen10 = [
   {
    bearName: "",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
]
//GEN 11
const gen11 = [
   {
    bearName: "",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
]
const gen12 = [
   {
    bearName: "",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
]
// GEN 13
const gen13 = [
   {
    bearName: "",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
]
const gen14 = [
   {
    bearName: "",
    year: "",
    generation: "14",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "",
    year: "",
    generation: "14",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "14",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "14",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "14",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "14",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "",
    year: "",
    generation: "14",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "14",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "14",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "14",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "14",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "14",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
]
const bearCubsSet1 = [
  {
    bearName: "",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

const bearCubsSet2 = [
  {
    bearName: "",
    year: "",
    generation: "Bear Cubs 2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "",
    year: "",
    generation: "Bear Cubs 2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Bear Cubs 2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Bear Cubs 2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Bear Cubs 2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Bear Cubs 2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "",
    year: "",
    generation: "Bear Cubs 2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Bear Cubs 2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Bear Cubs 2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Bear Cubs 2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "Bear Cubs 2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "Bear Cubs 2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

const limitedEdition = [
  {
    bearName: "Black Peter",
    year: "1998",
    generation: "Limited Edition",
    totalNum: "30,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "",
    year: "",
    generation: "Limited Edition",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Limited Edition",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Limited Edition",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Limited Edition",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Limited Edition",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "",
    year: "",
    generation: "Limited Edition",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Limited Edition",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Limited Edition",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Limited Edition",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "Limited Edition",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "Limited Edition",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

const usLimitedEdition = [
  {
    bearName: "",
    year: "",
    generation: "US Limited Edition",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "",
    year: "",
    generation: "US Limited Edition",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   
];

const holidayBears2001 = [
  {
    bearName: "",
    year: "",
    generation: "Holiday 2001",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "",
    year: "",
    generation: "Holiday 2001",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Holiday 2001",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Holiday 2001",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

const holidayBears2002 = [
  {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

const softBears12inch = [
  {
    bearName: "",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

const plushBears14inch = [
  {
    bearName: "",
    year: "",
    generation: "14 inch Plush Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "",
    year: "",
    generation: "14 inch Plush Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "14 inch Plush Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "14 inch Plush Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "14 inch Plush Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "14 inch Plush Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "",
    year: "",
    generation: "14 inch Plush Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "14 inch Plush Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "14 inch Plush Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "14 inch Plush Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "14 inch Plush Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "14 inch Plush Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  },
];

const backpacks = [
   {
    bearName: "",
    year: "",
    generation: "backpack",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "",
    year: "",
    generation: "backpack",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
 {
    bearName: "",
    year: "",
    generation: "backpack",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "",
    year: "",
    generation: "backpack",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];
// const gen2 = ["Jerry", "Crazy Fingers", "Dark Star", "Daydream", "Dupree", "Ripple", "Irie", "Sunshine", "Franklin", "Peggy-O"];

// const gen3 = ["Blues Man", "Foolish Heart", "China Cat", "Haight", "Ashbury", "Reuben", "August West", "Daisy", "Pearly Baker", "Doodah Man", "Uncle Sam", "Esau"];

// const gen4 = ["Candyman", "Deal", "Fall Tour", "Jack-A-Roe", "Snowflake", "Father Time", "Fire", "Lost Sailor", "Uncle John", "Scarlet", "Terrapin",];

// const gen5 = ["Aiko", "Bird Song", "CC Rider", "Dark Hollow", "Eyes Of The World", "Masterpiece", "Picasso Moon", "Shakedown", "Alligator"];

// const gen6 = ["Beauty", "Big Boss Man", "California", "Iris", "King Bee", "Love Light", "Mexicali", "Mr. Fantasy", "Lazy Lightning"];

// const gen7 = ["Baby Blue", "Baby Pink", "Butterfly", "Cherise", "Peace", "Spinner", "Summer Tour", "Sunflower", "Stealie"];

// const gen8 = ["Homer", "Aloha", "El Paso", "Treat", "Mind Bender", "Birthday Show"];

// const gen9 = ["Dread Head", "Prankster", "Warlock", "Puff", "Great Beyond", "Chillin", "Rudy", "Nicholas"];

// const gen10 = ["Friend O' Mine", "Mane Man", "Patriot", "Liberty", "Love Bug", "Funky", "Chops", "Ruby"];

// const gen11 = ["Ace", "Taffy", "Cheeky", "Quinn", "Powder", "Dustin"];

// const gen12 = ["Cream Puff", "Flower Power", "Memphis Blue", "Porky Way", "Shining Star", "Udder One"];

// const gen13 = ["Little Susie", "Katie Mae", "Phillmore", "Sugar Wags", "Tiger Billy", "Wharf Cat", "Shark Star"];

// const gen14 = ["Hot Spot", "Butterfinger", "Stretch", "Railroad Blue", "Chocolate Thunder", "Floyd"];

// const bearCubsSet1 = ["Lil Del", "Lil Star", "Lil Heart", "Lil Love", "Lil Sugar", "Lil Daisy"];

// const bearCubsSet2 = ["Lil Charlie", "Lil Samson", "Lil Sam", "Lil Snowflake", "Lil Doodah", "Lil Peggy"];

// const limitedEdition = ["All Access", "Cold Rain", "Poppa Bear", "Wharf Rat", "Mardi Gras", "Grate One", "Shoreline", "Vegas", "Black Peter", "Touch of Grey", "Casey Jones", "Devotion"];

// const usLimitedEdition = ["White Lightning", "Midnight"];

// const holidayBears2001 = ["The Grate Pumpkin", "Frosted"];

// const holidayBears2002 = ["Freedom", "Lucky"];

// const softBears12inch = ["Harmony", "Melody", "Rhythm", "Verse", "Jazz", "Blues"];

//const plushBears14inch = ["Lost Sailor", "Miracle", "Jack-A-Roe", "Spirit", "Sage", "Stella Blue", "Viola Lee", "Slipknot", "Rosalie McFall", "Black Peter", "Lucky", "Dread Head", "Foolish Heart", "Warlock", "Friend O' Mine", "Freedom", "Mane Man", "Chops", "Rudy", "Nick", "Blue Hare", "Ace"];

// const backpacks = ["Dark Star", "Foolish Heart", "Blue", "Teal"];
const bearData = {
  generations: { gen1, gen2, gen3, gen4, gen5, gen6, gen7, gen8, gen9, gen10, gen11, gen12, gen13, gen14,limitedEdition, holidayBears2001, bearCubsSet1, bearCubsSet2, limitedEdition, usLimitedEdition, softBears12inch, plushBears14inch, backpacks },
}