// const gen1 = ["Tennessee Jed", "Jack Straw", "Sugaree", "Althea", "Delilah", "St Stephen", "Cassidy", "Cosmic Charlie", "Samson", "Stagger Lee"];
//bear data = {

// }
const gen1 = [
  {
    bearName: "Tennessee Jed",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "6-27-87",
    tourMemory: "The Boston Garden 90.20.91 second set opener Help>Slip>Fire nearly blew my mind! I've never heard a crowd cheer so loudly. EVERYONE in the place was expecting Franklin's and they play Fire! I loved it when they mixed things up.",
    venue: "Alpine Valley",
    imagePath: "#",
  },
  {
    bearName: "Jack Straw",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "4-20-69",
    tourMemory: "cutting his buddy down",
    venue: "Witchita",
    imagePath: "#",
  },
   {
    bearName: "Sugaree",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "04/12/82",
    tourMemory: "My favorite show was on 4/12/89 at Rosemont, my only birthday show! They played everything I wanted to hear that night - it was like they could read my mind! It was the best birthday EVER.",
    venue: "Nassau Coliseum",
    imagePath: "#",
  },
   {
    bearName: "Althea",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "08/12/79",
    tourMemory: "The first nite of the Radio City run I lost my ticket, my money, everything. I was just about to call it a night when someone came up to me, handed me a ticket, and told me to have a good time. It was my first miracle. I'll never forget it!",
    venue: "Red Rocks",
    imagePath: "#",
  },
   {
    bearName: "Delilah",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "06/21/80",
    tourMemory: "The greatest time ever. Europe 1990. I sold some nonessential things, like my car, to finance my trip. The ICC in Berlin was a cool venue & the lamps on the tables helped with writing my set list. The Deal to close the first set was THE BEST!",
    venue: "West High Auditorium",
    imagePath: "#",
  },
   {
    bearName: "St Stephen",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "09/20/70",
    tourMemory: "Staying at the Desmond Americana for the Albany shows - we were smuggling our musical instruments through a window on the first floor when someone walked by, laughing loudly. Amp in hand, I turned to see the Fat Man himself.",
    venue: "Fillmore East",
    imagePath: "#",
  },
   {
    bearName: "Cassidy",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "04/20/69",
    tourMemory: "flight of the seabirds",
    venue: "bus",
    imagePath: "#",
  },
   {
    bearName: "Cosmic Charlie",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "03/03/90",
    tourMemory: "going marching in",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Samson",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "04/20/69",
    tourMemory: "i would tear this old building down",
    venue: "old building",
    imagePath: "#",
  },
   {
    bearName: "Stagger Lee",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "05/10/91",
    tourMemory: "A Terrapin Station anytime, any place! I loved it when Jerry really stepped out like on High Time or Stella Blue and of course Terrapin. He was definitely the leader of the band - which reminds me, Ramble on Rose rules too!",
    venue: "Shoreline Amphitheatre",
    imagePath: "#",
  },
  
];

const gen2 = [
  {
    bearName: "Jerry",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "As an icon for several generations and folk hero to many, Jerry Garcia & the Grateful Dead have influenced more people from more walks of life than any other musical group ever. Bringing their free form jams and San Francisco sound to countless cities around the globe for over thirty years, Jerry and The Dead became the most successful touring band in Rock history. Through his art, words and music, Jerry has inspired happiness, free thinking, and a lifestyle that has been adopted by people all around the world.",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Crazy Fingers",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Dark Star",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Daydream",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Dupree",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Ripple",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "Irie",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Sunshine",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Franklin",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Peggy-O",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

// GEN 3 

const gen3 = [
  {
    bearName: "Blues Man",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "A strong blues influence runs deep in the Grateful Dead and dates back to their formative days as The Warlocks. The Dead was blessed early on with one of the country's premier blues performers. He was known for his powerful vocals, and intense keyboard and harmonica playing. A crowd favorite, he could energize an entire show with his strong stage precense and his love of the music.",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Foolish Heart",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "08/28/88",
    tourMemory: "I was at a show at RFK, when I noticed a beautiful girl noticing me. We kept dancing closer and closer to each other until we finally spoke. We ended up dancing together all night. The show ended, we hugged and I left. I bought a rose the next night in hopes of seeing her again. I went to the same spot and there she was hoping to see me! We only knew each other for those two nights but I'll never forget her.",
    venue: "Autzen State",
    imagePath: "#",
  },
   {
    bearName: "China Cat",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "03/02/92",
    tourMemory: "I was at The Compton Terrace Ampitheatre in Arizona right before the show, waiting for it to start, when people started guessing what they might open with. I spoke up and said 'I feel something special about to happen.' Everyone laughed (I guess I've said this before) just as the opening notes of 'Here Comes Sunshine' started to fill the air. They hadn't played it in 18 years!",
    venue: "The Omni",
    imagePath: "#",
  },
   {
    bearName: "Haight",
    year: "1999",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Ashbury",
    year: "1999",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "03/03/68",
    tourMemory: "I was fortunate enough to make it all the way to Egypt to see my favorite band in the whole world. I had never even left the country before & I got my first passport just because of the Grateful Dead. The energy at those shows seemed almost out of this world.Something bigger than all of us was going on there, with the The Pyramids and The Sphinx. The local people really seemed psyched we were there. I still get chills when ever I think about it.",
    venue: "Haight Street",
    imagePath: "#",
  },
   {
    bearName: "Reuben",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "03/17/91",
    tourMemory: "The show at Nassau with Branford Marsalis is still one of my favorite shows ever. The band sounded so great with him playing with them. They all seemed to be having so much fun and the audience was absolutely losing thier minds. It was never my favorite venue, but it was rockin' that night for sure.",
    venue: "Capital Centre",
  },
   {
    bearName: "August West",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Daisy",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Pearly Baker",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Doodah Man",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Uncle Sam",
    year: "1999",
    generation: "3",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Esau",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
]

const gen4 = [
  {
    bearName: "Candyman",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "06/25/91",
    tourMemory: "The night of 'The Bubbles!' it seemed like everyone had bubbles and were blowing them all night long. Kinda like The Grateful Dead meets Lawrence Welk. There were two young kids in front of us and they had the best time of all. Blowing lots of little bubbles and then trying to blow huge ones. WE were all having so much fun! Who said Dead Heads were afraid of soap?",
    venue: "Sandstone Ampitheatre",
    imagePath: "#",
  },
  {
    bearName: "Deal",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "08/31/81",
    tourMemory: "I bought a ticket in the lot at Shoreline. I was headed into the show, when the ticket taker said my ticket was counterfeit. What a jones! I was making my way back to the lot and had given up all hope of getting in, when a limo pulled up next to me. A woman in back asked if I needed a ticket. I said, 'Yes,' and she handed me a ticket. She didn't want any money, I think she was my 'Ticket Fairy.'",
    venue: "Aladdin Theatre",
    imagePath: "#",
  },
   {
    bearName: "Fall Tour",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Jack-A-Roe",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Snowflake",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Father Time",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "Fire",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Lost Sailor",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Uncle John",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "05/02/70",
    tourMemory: "You never know who you might meet at a show. We were collecting funs to protect the Earth when a dirty hippie guy came up to the table. We told him about our cause like we do with everyone who will listen and he said he'd be right back. He came abck with a check for $1,000.00! Turns out he was a CEO of a major corporation and loved the Dead and the planet. Talk about not judging a book by its cover!",
    venue: "Harpur College",
    imagePath: "#",
  },
   {
    bearName: "Scarlet",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Terrapin",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  }
];

const gen5 = [
  {
    bearName: "Aiko",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Bird Song",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "CC Rider",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Dark Hollow",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "02/14/70",
    tourMemory: "I thought I had seen teh Dead do it all until I saw Phil play bass in a Barney costume. When he came out on stage it almost seemed natural to have a huge purple dinosaur on stage with the boys. He caused quite a stir with that one. I think some people were concerned that they were the only one seeing a purple dinosaur on stage. I thought it was funny.",
    venue: "Fillmore East",
    imagePath: "#",
  },
   {
    bearName: "Eyes of the World",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Masterpiece",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "Picasso Moon",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Shakedown",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Alligator",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  }
]
//GEN 6
const gen6 = [
   {
    bearName: "Lazy Lightning",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Beauty",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "11/70",
    tourMemory: "Coming out of a show at Giants Stadium still in post-concert elation, we realized we didn't know where our car was. We kept circling the stadium in a bigger and bigger spiral. Along the way we laughed, sang, met other post concert revelers, and kept on spiraling. Finally, around 3:30am there was our little red car coered in Dead stickers. This is how we invented 'The Spiral Dance of the Giants.'",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Big Boss Man",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "07/17/66",
    tourMemory: "It was June of '90. I was in the San Francisco Airport on my way to the Eugene, Oregon shows when I looked up and saw Jerry. I went over and introduced myself and told him I played in a band that played Grateful Dead music. He smiled and said 'Oh yeah? So do I.' We laughed and spoke for a short while. I did get his blessings to keep playing the Dead's stuff. He just said 'Do a good job of it.'",
    venue: "Fillmore Auditorium",
    imagePath: "#",
  },
   {
    bearName: "California",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Iris",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "King Bee",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "04/18/69",
    tourMemory: "I remember the first time I mail ordered for my tickets. I made sure I followed every direction 100%. I would have never forgiven myself if I made a mistake and didn't get my tickets. The first day the envelope could be post marked I'd be at the post office early that morning. I never waited in line for Dead tickets again. I used to draw cool pictures on the envelope to help make it stand out.",
    venue: "Memorial Union Ballroom",
  },
   {
    bearName: "Love Light",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "10/20/88",
    tourMemory: "One of the best thigns about tour was all my 'Tour friends' - the people you only saw on tour all over the country. I didn't even know a lot of their names but that hardly mattered. I'd get hugs and hang out with poeple for days on end and then not see them until our paths crossed again. You could tell who liked what cities and venues by running into them at the same places all the time on different tours.",
    venue: "The Summit",
    imagePath: "#",
  },
   {
    bearName: "Mexicali",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "10/19/71",
    tourMemory: "Camping was one of my favorite things to do on tour. Once, we traded tapes with some other heads in a rest stop and they invited us to the farm that they were camping out at for the show. People played instruments around a bonfire all night long. I've camped in national parks and even people's back yards, skinny dipped in ponds and cooked over wood fires. For me camping was the only way to do tour.",
    venue: "Northrop Auditorium",
    imagePath: "#",
  },
   {
    bearName: "Mr. Fantasy",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  }
]
const gen7 = [
   {
    bearName: "Stealie",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Baby Blue",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "01/07/66",
    tourMemory: "I was in this little country store in Buffalo when the woman behind the counter said to me, 'I love when the Grateful Dead come to town. You people are all so nice.' It made me feel good to know she thought I was nice and that I was one of 'those people.'",
    venue: "The Matrix",
    imagePath: "#",
  },
   {
    bearName: "Baby Pink",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Butterfly",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Cherise",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "03/17/91",
    tourMemory: "I still to this day can't get over how insane those two drummers played together. They totally grooved. They had two different styles that they combined together to make one magical sound. Bill and Mickey each knew what the other was going to do before the other one did. They kept everything together. Many a night they were the highlight of the show for me.",
    venue: "Capital Centre",
    imagePath: "#",
  },
   {
    bearName: "Spinner",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "Summer Tour",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Sunflower",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  }
]
const gen8 = [
   {
    bearName: "Homer",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Aloha",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "El Paso",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Treat",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Mind Bender",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "03/19/95",
    tourMemory: "My parents took me to my first show. After a few first set rockers, they began this spacey intro. My Dad started losing it, and hugging my Mom. Gradually the whole crowd recognized they were witnessing history. Afterward, everyone just stood at their seats exchanging high fives and embraces, That Father's Day I gave my Dad a pristine copy of 03/19/95, the first 'Unbroken Chain.'",
    venue: "The Spectrum",
    imagePath: "#",
  },
   {
    bearName: "Birthday Show",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
]
const gen9 = [
   {
    bearName: "Dread Head",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Prankster",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "10/11/84",
    tourMemory: "It's amazing how deadheads think alike and can read each other's minds. A buddy from work and I booked up to Maine on a THursday to see The Dead. Midway through the second set when they launched into 'Space' we simultaneously burst out laughing, celebrating the insanity on stage. The same thing happened for the encore, 'Day Job,' knowing that work on Friday was out of the question.",
    venue: "Augusta Civic Center",
    imagePath: "#",
  },
   {
    bearName: "Puff",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Great Beyond",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Chillin",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Rudy",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "Nicholas",
    year: "",
    generation: "9",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  
]
const gen10 = [
   {
    bearName: "Friend O' Mine",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Mane Man",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Patriot",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Liberty",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Love Bug",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Funky",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "Chops",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Ruby",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  }
]
//GEN 11
const gen11 = [
   {
    bearName: "Ace",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Taffy",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "03/19/73",
    tourMemory: "This is the Dead show I'll never forget. Early in the first set they started playing the opening riff to 'He's Gone.' A guy a few rows behind me started screaming, 'This one's for Pig. This one's for Pig!' It was bittersweet, but sweet nonetheless. I remember every one in the house singing with Jerry, 'Nothing left to do but smile, smile, smile... He's gone.' Very poignant.",
    venue: "Nassau Coliseum",
    imagePath: "#",
  },
   {
    bearName: "Cheeky",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Quinn",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Powder",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Dustin",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  }
]
const gen12 = [
  {
    bearName: "Cream Puff",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Flower Power",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Memphis Blue",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Porky Way",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Shining Star",
    year: "",
    generation: "12",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Udder One",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  }
];
// GEN 13
const gen13 = [
   {
    bearName: "Little Susie",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Katie Mae",
    year: "",
    generation: "13",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Phillmore",
    year: "",
    generation: "13",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Sugar Wags",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Tiger Billy",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Wharf Cat",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "Shark Star",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  }
  ]
const gen14 = [
   {
    bearName: "Hot Spot",
    year: "",
    generation: "14",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Butterfingers",
    year: "",
    generation: "14",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Stretch",
    year: "",
    generation: "14",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Railroad Blue",
    year: "",
    generation: "14",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Chocolate Thunder",
    year: "",
    generation: "14",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Floyd",
    year: "",
    generation: "14",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
  }
];

const gen15 = [
  {
    bearName: "",
    year: "",
    generation: "15",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },{
    bearName: "15",
    year: "",
    generation: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
]
const gen16 = [
  {
    bearName: "Mellow Yellow",
    year: "2010",
    generation: "16",
    totalNum: "500",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "Purple Craze",
    year: "2010",
    generation: "16",
    totalNum: "500",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "Fun Gus",
    year: "2010",
    generation: "16",
    totalNum: "500",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "Flower Child",
    year: "2010",
    generation: "16",
    totalNum: "500",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "",
    year: "",
    generation: "16",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
]

const bearCubsSet1 = [
  {
    bearName: "Lil Del",
    year: "2001",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Lil Star",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Lil Heart",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Lil Love",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Lil Sugar",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Lil Daisy",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
];

const bearCubsSet2 = [
  {
    bearName: "Lil Charlie",
    year: "2001",
    generation: "Bear Cubs 2",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Lil Samson",
    year: "2001",
    generation: "Bear Cubs 2",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Lil Sam",
    year: "2001",
    generation: "Bear Cubs 2",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Lil Snowflake",
    year: "2001",
    generation: "Bear Cubs 2",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Lil Doodah",
    year: "",
    generation: "Bear Cubs 2",
    inCollection: true,
    hasHangtag: true,
    birthday: "2001",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Lil Peggy",
    year: "2001",
    generation: "Bear Cubs 2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
];

const limitedEdition = [
  {
    bearName: "All Access",
    year: "1999",
    generation: "Limited Edition",
    totalNum: "52,800",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Cold Rain",
    year: "",
    generation: "Limited Edition",
    totalNum: "20,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Poppa Bear",
    year: "",
    generation: "Limited Edition",
    totalNum: "25,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Wharf Rat",
    year: "",
    generation: "Limited Edition",
    totalNum: "25,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Mardi Gras",
    year: "",
    generation: "Limited Edition",
    totalNum: "25,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Grate One",
    year: "2003",
    generation: "Limited Edition",
    totalNum: "9,999",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "Shoreline",
    year: "",
    generation: "Limited Edition",
    totalNum: "20,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Vegas",
    year: "",
    generation: "Limited Edition",
    totalNum: "20,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Black Peter",
    year: "1998",
    generation: "Limited Edition",
    totalNum: "30,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "03/25/91",
    tourMemory: "My favorite thing about being on your was that even someone you had never met before would rather say hi, flash you a great big smile or even give you a hug than just walk past you staring at their shoes. I wish it was always like that.",
    venue: "Knickerbocker Arena",
    imagePath: "#",
  },
   {
    bearName: "Touch of Grey",
    year: "",
    generation: "Limited Edition",
    totalNum: "25,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "10/09/82",
    tourMemory: "I wanted to go to my first Dead sshow, but my paretns said I was too young to go alone. My Mom said I could go as long as she went with me. It was better than not going, so we went. We actually hada  really great time, she loved it and so did I. I guess you're never too young or old to get hooked on the Dead. My Mom and I went to 33 shows. It's some of the best time we've ever spent together.",
    venue: "Frost Amphitheatre",
    imagePath: "#",
  },
 {
    bearName: "Casey Jones",
    year: "",
    generation: "Limited Edition",
    totalNum: "25,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Devotion",
    year: "20,000",
    generation: "Limited Edition",
    totalNum: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Error King Bee (Black Antennae)",
    year: "",
    generation: "Limited Edition",
    totalNum: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Error Delilah",
    year: "",
    generation: "Limited Edition",
    totalNum: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Liquid Blue Employee Bear",
    year: "2000",
    generation: "Limited Edition",
    totalNum: "160",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Devotion",
    year: "",
    generation: "Limited Edition",
    totalNum: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

const usLimitedEdition = [
  {
    bearName: "White Lightning",
    year: "",
    generation: "US Limited Edition",
    totalNum: "1200",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Midnight",
    year: "",
    generation: "US Limited Edition",
    totalNum: "1200",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

const holidayBears2001 = [
  {
    bearName: "Grate One",
    year: "2001",
    generation: "Holiday 2001",
    totalNum: "20,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Frosted",
    year: "2001",
    generation: "Holiday 2001",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

const holidayBears2002 = [
  {
    bearName: "Freedom",
    year: "2002",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Lucky",
    year: "2002",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

const softBears12inch = [
  {
    bearName: "Harmony",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Melody",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Rhythm",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Verse",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Jazz",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

const plushBears14inch = [
  {
    bearName: "Lost Sailor",
    year: "",
    totalNum: "4800",
    generation: "14 inch Plush Bears",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Miracle",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "4800",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Jack-A-Roe",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "4800",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Spirit",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "4800",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Sage",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "4800",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Stella Blue",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "4800",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "Viola Lee",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "3200",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Slipknot",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "3200",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Rosalie McFall",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "3200",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Black Peter",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "n/a",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Dread Head",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Lucky",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  },{
    bearName: "Foolish Heart",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Warlock",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  },{
    bearName: "Friend O' Mine",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Freedom",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Mane Man",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Chops",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Rudy",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Nick",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Blue Hare",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Ace",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  }, 
  {
    bearName: "Terrapin",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  },
];

const backpacks = [
   {
    bearName: "Dark Star",
    bearName: "",
    year: "",
    generation: "backpack",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    year: "Blue",
    generation: "backpack",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
 {
    bearName: "Foolish Heart",
    year: "",
    generation: "backpack",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Teal",
    year: "",
    generation: "backpack",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

const unknown = [
   {
    bearName: "Deadlocks",
    year: "2006",
    generation: "unknown",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "Grateful Red",
    year: "2006",
    generation: "unknown",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "Mane Squeeze",
    year: "2006",
    generation: "unknown",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "Black Throated",
    year: "2005",
    generation: "unknown",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "Blue Hare",
    year: "",
    generation: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "Countdown",
    year: "2007",
    generation: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "Psychedelic Shakedown",
    year: "",
    generation: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "Bunny Valentine",
    year: "",
    generation: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
    {
    bearName: "Smoke Stack",
    year: "",
    generation: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
    {
    bearName: "Bunny Valentine",
    year: "",
    generation: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
    {
    bearName: "Albino Samson",
    year: "",
    generation: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
    {
    bearName: "Albino Delilah",
    year: "",
    generation: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
    {
    bearName: "Mojo Hare",
    year: "",
    generation: "unknown",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
    {
    bearName: "Wicked",
    year: "2005",
    generation: "unknown",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
    {
    bearName: "Anthem of the Sun",
    year: "2018",
    generation: "unknown",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
    {
    bearName: "",
    year: "",
    generation: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
]

const bearData = {
  generations: { 
    gen1, 
    gen2, 
    gen3, 
    gen4, 
    gen5, 
    gen6, 
    gen7, 
    gen8, 
    gen9, 
    gen10, 
    gen11, 
    gen12, 
    gen13, 
    gen14,
    gen15,
    gen16,
    limitedEdition, 
    holidayBears2001,  
    bearCubsSet1, 
    bearCubsSet2, 
    limitedEdition, 
    usLimitedEdition, 
    softBears12inch, 
    plushBears14inch, 
    backpacks, 
    unknown 
  },
}