// const gen1 = ["Tennessee Jed", "Jack Straw", "Sugaree", "Althea", "Delilah", "St Stephen", "Cassidy", "Cosmic Charlie", "Samson", "Stagger Lee"];
//bear data = {

// }
const gen1 = [
  {
    bearName: "Tennessee Jed",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "6-27-87",
    tourMemory: "The Boston Garden 90.20.91 second set opener Help>Slip>Fire nearly blew my mind! I've never heard a crowd cheer so loudly. EVERYONE in the place was expecting Franklin's and they play Fire! I loved it when they mixed things up.",
    venue: "Alpine Valley",
    imagePath: "#",
  },
  {
    bearName: "Jack Straw",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "4-20-69",
    tourMemory: "lorem ipsum",
    venue: "lorem ipsum venue",
    imagePath: "#",
  },
   {
    bearName: "Sugaree",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "04/12/82",
    tourMemory: "My favorite show was on 4/12/89 at Rosemont, my only birthday show! They played everything I wanted to hear that night - it was like they could read my mind! It was the best birthday EVER.",
    venue: "Nassau Coliseum",
    imagePath: "#",
  },
   {
    bearName: "Althea",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "08/12/79",
    tourMemory: "The first nite of the Radio City run I lost my ticket, my money, everything. I was just about to call it a night when someone came up to me, handed me a ticket, and told me to have a good time. It was my first miracle. I'll never forget it!",
    venue: "Red Rocks",
    imagePath: "#",
  },
   {
    bearName: "Delilah",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "06/21/80",
    tourMemory: "The greatest time ever. Europe 1990. I sold some nonessential things, like my car, to finance my trip. The ICC in Berlin was a cool venue & the lamps on the tables helped with writing my set list. The Deal to close the first set was THE BEST!",
    venue: "West High Auditorium",
    imagePath: "#",
  },
   {
    bearName: "St Stephen",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "01/20/88",
    tourMemory: "wherever he goes the people all complain",
    venue: "garden",
    imagePath: "#",
  },
   {
    bearName: "Cassidy",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "04/20/69",
    tourMemory: "flight of the seabirds",
    venue: "bus",
    imagePath: "#",
  },
   {
    bearName: "Cosmic Charlie",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "03/03/90",
    tourMemory: "going marching in",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Samson",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "04/20/69",
    tourMemory: "i would tear this old building down",
    venue: "old building",
    imagePath: "#",
  },
   {
    bearName: "Stagger Lee",
    year: "1997",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "05/10/91",
    tourMemory: "A Terrapin Station anytime, any place! I loved it when Jerry really stepped out like on High Time or Stella Blue and of course Terrapin. He was definitely the leader of the band - which reminds me, Ramble on Rose rules too!",
    venue: "Shoreline Amphitheatre",
    imagePath: "#",
  },
  
];

const gen2 = [
  {
    bearName: "Jerry",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "6/27/87",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Crazy Fingers",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Dark Star",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Daydream",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Dupree",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Ripple",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "Irie",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Sunshine",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Franklin",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Peggy-O",
    year: "1998",
    generation: "2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

// GEN 3 

const gen3 = [
  {
    bearName: "Blues Man",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Foolish Heart",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "China Cat",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Haight",
    year: "1999",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Ashbury",
    year: "1999",
    generation: "1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Reuben",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "August West",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Daisy",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Pearly Baker",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Doodah Man",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Uncle Sam",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Esau",
    year: "1999",
    generation: "3",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
]

const gen4 = [
  {
    bearName: "Candyman",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Deal",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Fall Tour",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Jack-A-Roe",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Snowflake",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Father Time",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "Fire",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Lost Sailor",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Uncle John",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Scarlet",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Terrapin",
    year: "",
    generation: "4",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  }
];

const gen5 = [
  {
    bearName: "Aiko",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Bird Song",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "CC Rider",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Dark Hollow",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Eyes of the World",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Masterpiece",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "Picasso Moon",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Shakedown",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Alligator",
    year: "",
    generation: "5",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  }
]
//GEN 6
const gen6 = [
   {
    bearName: "Lazy Lightning",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Beauty",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Big Boss Man",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "California",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Iris",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "King Bee",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "Love Light",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Mexicali",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Mr. Fantasy",
    year: "",
    generation: "6",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  }
]
const gen7 = [
   {
    bearName: "Stealie",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Baby Blue",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Baby Pink",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Butterfly",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Cherise",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Spinner",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "Summer Tour",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Sunflower",
    year: "",
    generation: "7",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  }
]
const gen8 = [
   {
    bearName: "Homer",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Aloha",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "El Paso",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Treat",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Mind Bender",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Birthday Show",
    year: "",
    generation: "8",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
]
const gen9 = [
   {
    bearName: "Dread Head",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Prankster",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Puff",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Great Beyond",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Chillin",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Rudy",
    year: "",
    generation: "9",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "Nicholas",
    year: "",
    generation: "9",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  
]
const gen10 = [
   {
    bearName: "Friend O' Mine",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Mane Man",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Patriot",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Liberty",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Love Bug",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Funky",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "Chops",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Ruby",
    year: "",
    generation: "10",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  }
]
//GEN 11
const gen11 = [
   {
    bearName: "Ace",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Taffy",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Cheeky",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Quinn",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Powder",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Dustin",
    year: "",
    generation: "11",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  }
]
const gen12 = [
  {
    bearName: "Cream Puff",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Flower Power",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Memphis Blue",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Porky Way",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Shining Star",
    year: "",
    generation: "12",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Udder One",
    year: "",
    generation: "12",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  }
];
// GEN 13
const gen13 = [
   {
    bearName: "Little Susie",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Katie Mae",
    year: "",
    generation: "13",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Phillmore",
    year: "",
    generation: "13",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Sugar Wags",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Tiger Billy",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Wharf Cat",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "Shark Star",
    year: "",
    generation: "13",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  }
  ]
const gen14 = [
   {
    bearName: "Hot Spot",
    year: "",
    generation: "14",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Butterfingers",
    year: "",
    generation: "14",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Stretch",
    year: "",
    generation: "14",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Railroad Blue",
    year: "",
    generation: "14",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Chocolate Thunder",
    year: "",
    generation: "14",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Floyd",
    year: "",
    generation: "14",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
  }
];

const gen15 = [
  {
    bearName: "",
    year: "",
    generation: "15",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },{
    bearName: "15",
    year: "",
    generation: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
]
const gen16 = [
  {
    bearName: "Mellow Yellow",
    year: "2010",
    generation: "16",
    totalNum: "500",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "Purple Craze",
    year: "2010",
    generation: "16",
    totalNum: "500",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "Fun Gus",
    year: "2010",
    generation: "16",
    totalNum: "500",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "Flower Child",
    year: "2010",
    generation: "16",
    totalNum: "500",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "",
    year: "",
    generation: "16",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
]

const bearCubsSet1 = [
  {
    bearName: "Lil Del",
    year: "2001",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Lil Star",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Lil Heart",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Lil Love",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Lil Sugar",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Lil Daisy",
    year: "",
    generation: "Bear Cubs 1",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
];

const bearCubsSet2 = [
  {
    bearName: "Lil Charlie",
    year: "2001",
    generation: "Bear Cubs 2",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Lil Samson",
    year: "2001",
    generation: "Bear Cubs 2",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Lil Sam",
    year: "2001",
    generation: "Bear Cubs 2",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Lil Snowflake",
    year: "2001",
    generation: "Bear Cubs 2",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Lil Doodah",
    year: "",
    generation: "Bear Cubs 2",
    inCollection: true,
    hasHangtag: true,
    birthday: "2001",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Lil Peggy",
    year: "2001",
    generation: "Bear Cubs 2",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
];

const limitedEdition = [
  {
    bearName: "All Access",
    year: "1999",
    generation: "Limited Edition",
    totalNum: "52,800",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Cold Rain",
    year: "",
    generation: "Limited Edition",
    totalNum: "20,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Poppa Bear",
    year: "",
    generation: "Limited Edition",
    totalNum: "25,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Wharf Rat",
    year: "",
    generation: "Limited Edition",
    totalNum: "25,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Mardi Gras",
    year: "",
    generation: "Limited Edition",
    totalNum: "25,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Grate One",
    year: "2003",
    generation: "Limited Edition",
    totalNum: "9,999",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "Shoreline",
    year: "",
    generation: "Limited Edition",
    totalNum: "20,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Vegas",
    year: "",
    generation: "Limited Edition",
    totalNum: "20,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Black Peter",
    year: "1998",
    generation: "Limited Edition",
    totalNum: "30,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Touch of Grey",
    year: "",
    generation: "Limited Edition",
    totalNum: "25,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Casey Jones",
    year: "",
    generation: "Limited Edition",
    totalNum: "25,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Devotion",
    year: "20,000",
    generation: "Limited Edition",
    totalNum: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Error King Bee (Black Antennae)",
    year: "",
    generation: "Limited Edition",
    totalNum: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Error Delilah",
    year: "",
    generation: "Limited Edition",
    totalNum: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Liquid Blue Employee Bear",
    year: "2000",
    generation: "Limited Edition",
    totalNum: "160",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Devotion",
    year: "",
    generation: "Limited Edition",
    totalNum: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

const usLimitedEdition = [
  {
    bearName: "White Lightning",
    year: "",
    generation: "US Limited Edition",
    totalNum: "1200",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Midnight",
    year: "",
    generation: "US Limited Edition",
    totalNum: "1200",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

const holidayBears2001 = [
  {
    bearName: "Grate One",
    year: "2001",
    generation: "Holiday 2001",
    totalNum: "20,000",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Frosted",
    year: "2001",
    generation: "Holiday 2001",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

const holidayBears2002 = [
  {
    bearName: "Freedom",
    year: "2002",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Lucky",
    year: "2002",
    generation: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

const softBears12inch = [
  {
    bearName: "Harmony",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Melody",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Rhythm",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Verse",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Jazz",
    year: "",
    generation: "Soft 12 inch Bears",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

const plushBears14inch = [
  {
    bearName: "Lost Sailor",
    year: "",
    totalNum: "4800",
    generation: "14 inch Plush Bears",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Miracle",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "4800",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Jack-A-Roe",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "4800",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Spirit",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "4800",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Sage",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "4800",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Stella Blue",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "4800",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
   {
    bearName: "Viola Lee",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "3200",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Slipknot",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "3200",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Rosalie McFall",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "3200",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    bearName: "Black Peter",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "n/a",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Dread Head",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Lucky",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  },{
    bearName: "Foolish Heart",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Warlock",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  },{
    bearName: "Friend O' Mine",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Freedom",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Mane Man",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Chops",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Rudy",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Nick",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Blue Hare",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  },
  {
    bearName: "Ace",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  }, 
  {
    bearName: "Terrapin",
    year: "",
    generation: "14 inch Plush Bears",
    totalNum: "",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "14 inch Plush Bears",
    venue: "",
    imagePath: "#",
  },
];

const backpacks = [
   {
    bearName: "Dark Star",
    bearName: "",
    year: "",
    generation: "backpack",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
   {
    year: "Blue",
    generation: "backpack",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
  },
 {
    bearName: "Foolish Heart",
    year: "",
    generation: "backpack",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
 {
    bearName: "Teal",
    year: "",
    generation: "backpack",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
  },
];

const unknown = [
   {
    bearName: "Deadlocks",
    year: "2006",
    generation: "unknown",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "Grateful Red",
    year: "2006",
    generation: "unknown",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "Mane Squeeze",
    year: "2006",
    generation: "unknown",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "Black Throated",
    year: "2005",
    generation: "unknown",
    inCollection: true,
    hasHangtag: true,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "Blue Hare",
    year: "",
    generation: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "Countdown",
    year: "2007",
    generation: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "Psychedelic Shakedown",
    year: "",
    generation: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
   {
    bearName: "Bunny Valentine",
    year: "",
    generation: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
    {
    bearName: "Smoke Stack",
    year: "",
    generation: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
    {
    bearName: "Bunny Valentine",
    year: "",
    generation: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
    {
    bearName: "Albino Samson",
    year: "",
    generation: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
    {
    bearName: "Albino Delilah",
    year: "",
    generation: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
    {
    bearName: "Mojo Hare",
    year: "",
    generation: "unknown",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
    {
    bearName: "Wicked",
    year: "2005",
    generation: "unknown",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
    {
    bearName: "Anthem of the Sun",
    year: "2018",
    generation: "unknown",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
    {
    bearName: "",
    year: "",
    generation: "",
    inCollection: false,
    hasHangtag: false,
    birthday: "",
    tourMemory: "",
    venue: "",
    imagePath: "#",
   },
]

const bearData = {
  generations: { 
    gen1, 
    gen2, 
    gen3, 
    gen4, 
    gen5, 
    gen6, 
    gen7, 
    gen8, 
    gen9, 
    gen10, 
    gen11, 
    gen12, 
    gen13, 
    gen14,
    gen15,
    gen16,
    limitedEdition, 
    holidayBears2001,  
    bearCubsSet1, 
    bearCubsSet2, 
    limitedEdition, 
    usLimitedEdition, 
    softBears12inch, 
    plushBears14inch, 
    backpacks, 
    unknown 
  },
}